// This file will be auto-generated by Supabase CLI: npx supabase gen types typescript
// For now, we define a placeholder structure

// Verification status for therapists and practices
export type VerificationStatus =
	| 'unverified'
	| 'pending'
	| 'identity_verified'
	| 'credential_verified'
	| 'fully_verified';

// Practice/clinic types
export type PracticeType = 'solo' | 'group' | 'clinic' | 'franchise';

// Practice member roles
export type PracticeRole = 'owner' | 'admin' | 'manager' | 'therapist' | 'receptionist';

export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json | undefined }
	| Json[];

export interface Database {
	public: {
		Tables: {
			users: {
				Row: {
					id: string;
					email: string;
					full_name: string | null;
					phone: string | null;
					avatar_url: string | null;
					role: 'client' | 'therapist' | 'admin';
					locale: string;
					email_preferences: Json | null;
					referred_by_code: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					email: string;
					full_name?: string | null;
					phone?: string | null;
					avatar_url?: string | null;
					role?: 'client' | 'therapist' | 'admin';
					locale?: string;
					email_preferences?: Json | null;
					referred_by_code?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					email?: string;
					full_name?: string | null;
					phone?: string | null;
					avatar_url?: string | null;
					role?: 'client' | 'therapist' | 'admin';
					locale?: string;
					email_preferences?: Json | null;
					referred_by_code?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			therapists: {
				Row: {
					id: string;
					user_id: string;
					bio: string | null;
					years_of_experience: number | null;
					certification_details: Json | null;
					location: unknown; // PostGIS POINT
					service_radius_km: number;
					rating_avg: number;
					rating_count: number;
					vetting_status: 'pending' | 'approved' | 'rejected';
					is_available: boolean;
					timezone: string;
					colectiva_wallet_id: string | null;
					ecosystem_org_id: string | null;
					subscription_tier: 'free' | 'pro' | 'business' | 'enterprise';
					is_featured: boolean;
					featured_until: string | null;
					monthly_booking_count: number;
					// Verification fields
					verification_status: VerificationStatus;
					verification_submitted_at: string | null;
					verification_completed_at: string | null;
					verification_documents: Json;
					id_document_verified: boolean;
					license_verified: boolean;
					background_check_passed: boolean;
					// Practice association
					is_independent: boolean;
					primary_practice_id: string | null;
					// Scheduling preferences
					smart_schedule_grouping: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					bio?: string | null;
					years_of_experience?: number | null;
					certification_details?: Json | null;
					location?: unknown;
					service_radius_km?: number;
					rating_avg?: number;
					rating_count?: number;
					vetting_status?: 'pending' | 'approved' | 'rejected';
					is_available?: boolean;
					timezone?: string;
					colectiva_wallet_id?: string | null;
					ecosystem_org_id?: string | null;
					subscription_tier?: 'free' | 'pro' | 'business' | 'enterprise';
					is_featured?: boolean;
					featured_until?: string | null;
					monthly_booking_count?: number;
					verification_status?: VerificationStatus;
					verification_submitted_at?: string | null;
					verification_completed_at?: string | null;
					verification_documents?: Json;
					id_document_verified?: boolean;
					license_verified?: boolean;
					background_check_passed?: boolean;
					is_independent?: boolean;
					primary_practice_id?: string | null;
					smart_schedule_grouping?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					bio?: string | null;
					years_of_experience?: number | null;
					certification_details?: Json | null;
					location?: unknown;
					service_radius_km?: number;
					rating_avg?: number;
					rating_count?: number;
					vetting_status?: 'pending' | 'approved' | 'rejected';
					is_available?: boolean;
					timezone?: string;
					colectiva_wallet_id?: string | null;
					ecosystem_org_id?: string | null;
					subscription_tier?: 'free' | 'pro' | 'business' | 'enterprise';
					is_featured?: boolean;
					featured_until?: string | null;
					monthly_booking_count?: number;
					verification_status?: VerificationStatus;
					verification_submitted_at?: string | null;
					verification_completed_at?: string | null;
					verification_documents?: Json;
					id_document_verified?: boolean;
					license_verified?: boolean;
					background_check_passed?: boolean;
					is_independent?: boolean;
					primary_practice_id?: string | null;
					smart_schedule_grouping?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			practices: {
				Row: {
					id: string;
					name: string;
					slug: string | null;
					description: string | null;
					logo_url: string | null;
					cover_image_url: string | null;
					business_type: PracticeType;
					tax_id: string | null;
					business_license: string | null;
					email: string;
					phone: string | null;
					website: string | null;
					address: string | null;
					city: string | null;
					state: string | null;
					postal_code: string | null;
					country: string;
					location: unknown | null;
					verification_status: VerificationStatus;
					verification_submitted_at: string | null;
					verification_completed_at: string | null;
					verification_documents: Json;
					verification_notes: string | null;
					timezone: string;
					currency: string;
					booking_settings: Json;
					ecosystem_org_id: string | null;
					colectiva_wallet_id: string | null;
					subscription_tier: string;
					subscription_status: string;
					rating_avg: number;
					rating_count: number;
					total_bookings: number;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					slug?: string | null;
					description?: string | null;
					logo_url?: string | null;
					cover_image_url?: string | null;
					business_type?: PracticeType;
					tax_id?: string | null;
					business_license?: string | null;
					email: string;
					phone?: string | null;
					website?: string | null;
					address?: string | null;
					city?: string | null;
					state?: string | null;
					postal_code?: string | null;
					country?: string;
					location?: unknown | null;
					verification_status?: VerificationStatus;
					verification_submitted_at?: string | null;
					verification_completed_at?: string | null;
					verification_documents?: Json;
					verification_notes?: string | null;
					timezone?: string;
					currency?: string;
					booking_settings?: Json;
					ecosystem_org_id?: string | null;
					colectiva_wallet_id?: string | null;
					subscription_tier?: string;
					subscription_status?: string;
					rating_avg?: number;
					rating_count?: number;
					total_bookings?: number;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					name?: string;
					slug?: string | null;
					description?: string | null;
					logo_url?: string | null;
					cover_image_url?: string | null;
					business_type?: PracticeType;
					tax_id?: string | null;
					business_license?: string | null;
					email?: string;
					phone?: string | null;
					website?: string | null;
					address?: string | null;
					city?: string | null;
					state?: string | null;
					postal_code?: string | null;
					country?: string;
					location?: unknown | null;
					verification_status?: VerificationStatus;
					verification_submitted_at?: string | null;
					verification_completed_at?: string | null;
					verification_documents?: Json;
					verification_notes?: string | null;
					timezone?: string;
					currency?: string;
					booking_settings?: Json;
					ecosystem_org_id?: string | null;
					colectiva_wallet_id?: string | null;
					subscription_tier?: string;
					subscription_status?: string;
					rating_avg?: number;
					rating_count?: number;
					total_bookings?: number;
					created_at?: string;
					updated_at?: string;
				};
			};
			practice_members: {
				Row: {
					id: string;
					practice_id: string;
					user_id: string;
					therapist_id: string | null;
					role: PracticeRole;
					permissions: Json;
					title: string | null;
					hire_date: string | null;
					commission_rate: number | null;
					status: string;
					invited_at: string | null;
					joined_at: string | null;
					invited_by: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					practice_id: string;
					user_id: string;
					therapist_id?: string | null;
					role?: PracticeRole;
					permissions?: Json;
					title?: string | null;
					hire_date?: string | null;
					commission_rate?: number | null;
					status?: string;
					invited_at?: string | null;
					joined_at?: string | null;
					invited_by?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					practice_id?: string;
					user_id?: string;
					therapist_id?: string | null;
					role?: PracticeRole;
					permissions?: Json;
					title?: string | null;
					hire_date?: string | null;
					commission_rate?: number | null;
					status?: string;
					invited_at?: string | null;
					joined_at?: string | null;
					invited_by?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			practice_invitations: {
				Row: {
					id: string;
					practice_id: string;
					email: string;
					role: PracticeRole;
					title: string | null;
					token: string;
					expires_at: string;
					status: string;
					invited_by: string | null;
					accepted_by: string | null;
					accepted_at: string | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					practice_id: string;
					email: string;
					role?: PracticeRole;
					title?: string | null;
					token: string;
					expires_at: string;
					status?: string;
					invited_by?: string | null;
					accepted_by?: string | null;
					accepted_at?: string | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					practice_id?: string;
					email?: string;
					role?: PracticeRole;
					title?: string | null;
					token?: string;
					expires_at?: string;
					status?: string;
					invited_by?: string | null;
					accepted_by?: string | null;
					accepted_at?: string | null;
					created_at?: string;
				};
			};
			categories: {
				Row: {
					id: string;
					name: string;
					name_es: string;
					slug: string;
					icon: string | null;
					description: string | null;
					sort_order: number;
					created_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					name_es: string;
					slug: string;
					icon?: string | null;
					description?: string | null;
					sort_order?: number;
					created_at?: string;
				};
				Update: {
					id?: string;
					name?: string;
					name_es?: string;
					slug?: string;
					icon?: string | null;
					description?: string | null;
					sort_order?: number;
					created_at?: string;
				};
			};
			services: {
				Row: {
					id: string;
					category_id: string;
					name: string;
					name_es: string;
					description: string | null;
					description_es: string | null;
					default_duration_minutes: number;
					default_price_cents: number;
					is_active: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					category_id: string;
					name: string;
					name_es: string;
					description?: string | null;
					description_es?: string | null;
					default_duration_minutes?: number;
					default_price_cents?: number;
					is_active?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					category_id?: string;
					name?: string;
					name_es?: string;
					description?: string | null;
					description_es?: string | null;
					default_duration_minutes?: number;
					default_price_cents?: number;
					is_active?: boolean;
					created_at?: string;
				};
			};
			therapist_services: {
				Row: {
					id: string;
					therapist_id: string;
					service_id: string;
					price_cents: number;
					duration_minutes: number;
					is_active: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					therapist_id: string;
					service_id: string;
					price_cents: number;
					duration_minutes: number;
					is_active?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					therapist_id?: string;
					service_id?: string;
					price_cents?: number;
					duration_minutes?: number;
					is_active?: boolean;
					created_at?: string;
				};
			};
			bookings: {
				Row: {
					id: string;
					client_id: string;
					therapist_id: string;
					therapist_service_id: string;
					scheduled_at: string;
					scheduled_end_at: string;
					status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					price_cents: number;
					commission_cents: number;
					therapist_payout_cents: number;
					distance_km: number | null;
					distance_fee_cents: number;
					service_modality: 'home_visit' | 'studio_visit' | 'neutral_location';
					client_address: string | null;
					client_location: unknown | null;
					notes: string | null;
					source: string;
					escrow_id: string | null;
					reminder_24h_sent_at: string | null;
					reminder_1h_sent_at: string | null;
					completed_at: string | null;
					completed_by: string | null;
					cancelled_at: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					client_id: string;
					therapist_id: string;
					therapist_service_id: string;
					scheduled_at: string;
					scheduled_end_at: string;
					status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					price_cents: number;
					commission_cents?: number;
					therapist_payout_cents?: number;
					distance_km?: number | null;
					distance_fee_cents?: number;
					service_modality?: 'home_visit' | 'studio_visit' | 'neutral_location';
					client_address?: string | null;
					client_location?: unknown | null;
					notes?: string | null;
					source?: string;
					escrow_id?: string | null;
					reminder_24h_sent_at?: string | null;
					reminder_1h_sent_at?: string | null;
					completed_at?: string | null;
					completed_by?: string | null;
					cancelled_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					client_id?: string;
					therapist_id?: string;
					therapist_service_id?: string;
					scheduled_at?: string;
					scheduled_end_at?: string;
					status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					price_cents?: number;
					commission_cents?: number;
					therapist_payout_cents?: number;
					distance_km?: number | null;
					distance_fee_cents?: number;
					service_modality?: 'home_visit' | 'studio_visit' | 'neutral_location';
					client_address?: string | null;
					client_location?: unknown | null;
					notes?: string | null;
					source?: string;
					escrow_id?: string | null;
					reminder_24h_sent_at?: string | null;
					reminder_1h_sent_at?: string | null;
					completed_at?: string | null;
					completed_by?: string | null;
					cancelled_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			reviews: {
				Row: {
					id: string;
					booking_id: string;
					client_id: string;
					therapist_id: string;
					rating: number;
					comment: string | null;
					therapist_response: string | null;
					is_public: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					booking_id: string;
					client_id: string;
					therapist_id: string;
					rating: number;
					comment?: string | null;
					therapist_response?: string | null;
					is_public?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					booking_id?: string;
					client_id?: string;
					therapist_id?: string;
					rating?: number;
					comment?: string | null;
					therapist_response?: string | null;
					is_public?: boolean;
					created_at?: string;
				};
			};
			tips: {
				Row: {
					id: string;
					booking_id: string;
					client_id: string;
					therapist_id: string;
					amount_cents: number;
					plenura_fee_cents: number;
					therapist_amount_cents: number;
					created_at: string;
				};
				Insert: {
					id?: string;
					booking_id: string;
					client_id: string;
					therapist_id: string;
					amount_cents: number;
					plenura_fee_cents?: number;
					therapist_amount_cents: number;
					created_at?: string;
				};
				Update: {
					id?: string;
					booking_id?: string;
					client_id?: string;
					therapist_id?: string;
					amount_cents?: number;
					plenura_fee_cents?: number;
					therapist_amount_cents?: number;
					created_at?: string;
				};
			};
			availability: {
				Row: {
					id: string;
					therapist_id: string;
					day_of_week: number;
					start_time: string;
					end_time: string;
					is_active: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					therapist_id: string;
					day_of_week: number;
					start_time: string;
					end_time: string;
					is_active?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					therapist_id?: string;
					day_of_week?: number;
					start_time?: string;
					end_time?: string;
					is_active?: boolean;
					created_at?: string;
				};
			};
			referral_codes: {
				Row: {
					id: string;
					user_id: string;
					code: string;
					reward_amount_cents: number;
					uses_count: number;
					max_uses: number | null;
					is_active: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					code: string;
					reward_amount_cents?: number;
					uses_count?: number;
					max_uses?: number | null;
					is_active?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					code?: string;
					reward_amount_cents?: number;
					uses_count?: number;
					max_uses?: number | null;
					is_active?: boolean;
					created_at?: string;
				};
			};
			referrals: {
				Row: {
					id: string;
					referral_code_id: string;
					referred_user_id: string;
					status: 'pending' | 'completed' | 'cancelled';
					reward_paid_cents: number | null;
					completed_at: string | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					referral_code_id: string;
					referred_user_id: string;
					status?: 'pending' | 'completed' | 'cancelled';
					reward_paid_cents?: number | null;
					completed_at?: string | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					referral_code_id?: string;
					referred_user_id?: string;
					status?: 'pending' | 'completed' | 'cancelled';
					reward_paid_cents?: number | null;
					completed_at?: string | null;
					created_at?: string;
				};
			};
			favorites: {
				Row: {
					id: string;
					user_id: string;
					therapist_id: string;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id?: string;
					therapist_id: string;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					therapist_id?: string;
					created_at?: string;
				};
			};
		};
		Views: {};
		Functions: {
			search_therapists_nearby: {
				Args: {
					lat: number;
					lng: number;
					radius_km: number;
					category_slug?: string;
					service_id?: string;
				};
				Returns: Array<{
					id: string;
					user_id: string;
					full_name: string;
					avatar_url: string;
					bio: string;
					rating_avg: number;
					rating_count: number;
					distance_km: number;
					min_price_cents: number;
					services: Json;
				}>;
			};
		};
		Enums: {
			user_role: 'client' | 'therapist' | 'admin';
			booking_status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
			vetting_status: 'pending' | 'approved' | 'rejected';
			subscription_tier: 'free' | 'pro' | 'business' | 'enterprise';
			service_modality: 'home_visit' | 'studio_visit' | 'neutral_location';
			verification_status: VerificationStatus;
			practice_type: PracticeType;
			practice_role: PracticeRole;
		};
	};
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];

// Convenience types
export type User = Tables<'users'>;
export type Therapist = Tables<'therapists'>;
export type Practice = Tables<'practices'>;
export type PracticeMember = Tables<'practice_members'>;
export type PracticeInvitation = Tables<'practice_invitations'>;
export type Category = Tables<'categories'>;
export type Service = Tables<'services'>;
export type TherapistService = Tables<'therapist_services'>;
export type Booking = Tables<'bookings'>;
export type Review = Tables<'reviews'>;
export type Availability = Tables<'availability'>;
export type ReferralCode = Tables<'referral_codes'>;
export type Tip = Tables<'tips'>;

// Verification badge info helper
export interface VerificationBadgeInfo {
	status: VerificationStatus;
	label: string;
	description: string;
	color: 'gray' | 'yellow' | 'blue' | 'green' | 'purple';
	icon: string;
}

export const VERIFICATION_BADGES: Record<VerificationStatus, VerificationBadgeInfo> = {
	unverified: {
		status: 'unverified',
		label: 'Sin verificar',
		description: 'Este perfil aún no ha sido verificado',
		color: 'gray',
		icon: 'shield-x'
	},
	pending: {
		status: 'pending',
		label: 'En revisión',
		description: 'Documentos enviados, en proceso de verificación',
		color: 'yellow',
		icon: 'shield-clock'
	},
	identity_verified: {
		status: 'identity_verified',
		label: 'Identidad verificada',
		description: 'Identidad confirmada con documento oficial',
		color: 'blue',
		icon: 'shield-check'
	},
	credential_verified: {
		status: 'credential_verified',
		label: 'Profesional verificado',
		description: 'Licencia profesional y credenciales verificadas',
		color: 'green',
		icon: 'shield-star'
	},
	fully_verified: {
		status: 'fully_verified',
		label: 'Verificación completa',
		description: 'Todas las verificaciones completadas incluyendo antecedentes',
		color: 'purple',
		icon: 'shield-crown'
	}
};
